server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/result_bot
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: janobprizident@gmail.com
    password: ecgyiraunmdyakcg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  jwt:
    secret-key: ymanDxgNwmCoYxrg7SWawCN8hbyBWz/ZSalfMmhJspk=
    expiration-time: 2628000000
    refresh-expiration-time: 864000000
telegram:
  bot:
    username: result_finance_bot
    token: 7902141440:AAGvYkmtNlFozsZCbGO8m3ER70RIVl2Jyog
    webhook-path: https://fbca-91-90-219-96.ngrok-free.app/telegram/webhook